import React from 'react'
import { Box, Container, Typography, } from '@mui/material'


export default function TermsConditions() {
  return (
    <>
        <Box className='dsbrd_main_bx '>
          <Container>
              <Box className='title_hding'>
                <Typography component='h1'>Registration clause</Typography>
                <Typography>Athenacryptobank.io is owned by Athena LLC. athenacryptobank is fully managed by Athena LLC. Any functions, facilities, applications, information or other services and names available through this website are solely related and belongs and refers to the saint vincent and the grenadines registered company Athena LLC.Currently, Athena Crypto Bank does not provide services for users from the following countries / areas: China, Japan, Republic of The Sudan, The Syrian Arab Republic, North Korea (Democratic People's Republic of Korea), Islamic Republic of Iran, Republic of Liberia, The Republic of Cuba, The Republic of Côte d'Ivoire, The Republic of North Macedonia, The Republic of South Sudan, Republic of Belarus, The Republic of Congo, The Democratic Republic of the Congo, The Republic of Zimbabwe, Central African Republic, Republic of Albania, Republic of Lebanon, State of Lybia, The State of Eritrea, The Federal Republic of Somalia, The Republic of the Union of Myanmar, Yemen Republic, The Islamic Republic of Afghanistan, United States, Republic of Iraq, Bosnia and Herzegovina, The Republic of Burundi, Republic of Chad, Bolivarian Republic of Venezuela</Typography>
                <Typography component='h1'>Terms of Service</Typography>
                <Typography>Use of this Athena Crypto Bank website (“Website”) and the service offered on the Website (“Service”) are governed by the terms contained on this Terms and Conditions page (“Terms”). This agreement entirely constitutes the agreement between the parties. All other information provided on the Website or oral/written statements made are excluded from this agreement; the exchange policy is provided for guidance only and does not constitute a legal agreement between the parties.</Typography>
                <Typography>By accessing, viewing or downloading information from the Website and using the Service provided by Athena Crypto Bank you you acknowledge that you have read,understood and unconditionally agreed to be bound by these Terms. Athena Crypto Bank may at any time without notice amend these Terms. You agree to continue to be bound by any amended terms and conditions and that Athena Crypto Bank has no obligation to notify you of such amendments. You acknowledge that it is your responsibility to check these Terms periodically for changes and that your continued use of the Website and Services offered by Athena Crypto Bank following the posting of any changes to the Terms indicates your acceptance of any such changes.</Typography>
                <Typography>The Website and the copyright in all text, graphics, images, software and any other materials on the Website is owned by Athena Crypto Bank including all trademarks and other intellectual property rights in respect of materials and Service on the Website. Materials on this Website may only be used for personal use and non-commercial purposes.</Typography>
                <Typography>You shall not in any circumstances obtain any rights over or in respect of the Website (other than rights to use the Website pursuant to these Terms and any other terms and conditions governing a particular service or section of the Website) or hold yourself out as having any such rights over or in respect of the Website.</Typography>
                <Typography component='h1'>Important Reminder:</Typography>
                <Typography>The digital assets themselves are not offered by any financial institution, corporation or this website.</Typography>
                <ol className='ol_li_mar_btm'>
                  <li>The digital asset market is new and unconfirmed, and will not necessarily expand.</li>
                  <li>Digital assets are primarily used by speculators, and are used relatively less on retail and commercial markets. Digital asset transactions are highly risky, due to the fact that they are traded throughout 24-hours a day without limits on the rise or fall in price, and market makers and global government policies may cause major fluctuations in their prices.</li>
                  <li>Digital asset transactions may be suspended or prohibited at any time due to the enactment or modification of national laws, regulations and regulatory documents.</li>
                  <li>The Services are intended solely for users who are 18 or older. By accessing or using our Services, you represent and warrant that you are at least 18 years old and have not previously been suspended or removed from the Site or Services. </li>
                  <li>You understand that this website is only intended to serve as an avenue  for you to obtain digital asset information, find trading counterparties, hold negotiations on and effect transactions of digital assets. This website does not participate in any of your transactions, and therefore you shall, at your sole discretion, carefully assess the authenticity, legality and validity of relevant digital assets and/or information, and solely bear the responsibilities and losses that may arise therefore.</li>
                  <li>All opinions, information, discussions, analyses, prices, advice and other information on this website are general market reviews and do not constitute any investment advice. We do not bear any loss arising directly or indirectly from reliance on the above-mentioned information, including but not limited to, any loss of profits.</li>
                  <li>Using internet-based trading systems also involves risks, including but not limited to failures in software, hardware or Internet links, etc. In view of the fact that we cannot control the reliability and availability of the Internet, we will not be responsible for any distortion, delay and link failure.</li>
                  <li>It is prohibited to use this website for any illegal activities, such as money-laundering, smuggling and commercial bribery. Upon uncovering any of such illegal activities, this website will adopt all available measures, including but not limited to freezing accounts, notifying the relevant authorities and so on, and in this case, we shall not assume any of the responsibilities arising therefrom, and reserve the right to hold the relevant persons accountable.</li>
                </ol>
                <Typography component='h1'>Account Registration</Typography>
                <Typography>Registration is done via Metamask or Trustwallet. By pushing on connect, you allow Athena Crypto Bank to read your wallet and register on the platform.</Typography>
                <Typography>The user has the right to choose whether to become the Athena Crypto Bank network's users. If users choose to become Athena Crypto Bank registered users, they can create their nicknames. Usernames and nicknames shall abide by relevant laws and regulations and also in accordance with the network morality. Usernames and nicknames cannot contain any words which related to insults, threats, obscene, abuse and other violations of the legitimate rights and interests of others.</Typography>
                
                <Typography component='h1'>Termination of Agreement</Typography>
                <Typography>You hereby agree that, Athena Crypto Bank shall have the right to terminate all or part of Athena Crypto Bank Service to you, temporarily freeze or permanently freeze (cancel) the authorizations of your account on Athena Crypto Bank at Athena Crypto Bank's sole discretion, without any prior notice, for whatsoever reason, and Athena Crypto Bank shall not be liable to you; however, Athena Crypto Bank shall have the right to keep and use the transaction data, records and other information that is related to such account. In case of any of the following events, Athena Crypto Bank shall have the right to directly terminate this agreement by cancelling your account, and shall have the right to permanently freeze (cancel) the authorizations of your account on Athena Crypto Bank and withdraw the corresponding Athena Crypto Bank account there of:</Typography>
                <ol  className='ol_li_mar_btm'>
                  <li>After Athena Crypto Bank terminates services to you, you allegedly register or register in any other person’s name as Athena Crypto Bank user again, directly or indirectly;</li>
                  <li>The main content of user’s information that you have provided is untruthful, inaccurate, outdated or incomplete; when this agreement (including the rules) is amended, you expressly state and notify Athena Crypto Bank of your unwillingness to accept the amended service agreement.</li>
                </ol>
                <Typography>After the account service is terminated or the authorizations of your account on Athena Crypto Bank is permanently froze (cancelled), Athena Crypto Bank shall not have any duty to keep or disclose to you any information in your account or forward any information you have not read or sent to you or any third party.</Typography>
                <Typography>You agree that, after the termination of agreement between you and Athena Crypto Bank , Athena Crypto Bank shall still have the rights to: keep your user’s information and all the transaction information during your use of Athena Crypto Bank Service. Claim against you according to this agreement if you have violated any laws, this agreement or the rules during your use of Athena Crypto Bank Service. After Athena Crypto Bank suspends or terminates Athena Crypto Bank Service to you, your transaction activities prior to such suspension or termination will be dealt with according to the following principles and you shall will take care of on your own efforts and fully undertake any disputes, losses or extra expenses caused thereby and keep Athena Crypto Bank harmless from any losses or expenses: Athena Crypto Bank shall have the right to delete, at the same time of suspension or termination of services, information related to any un-traded coin tokens that you have uploaded to Athena Crypto Bank prior to the suspension or termination. If you have reached any purchase agreement with any other member prior to the suspension or termination but such agreement has not been actually performed, Athena Crypto Bank shall have the right to delete information related to such purchase agreement and the coins in question. If you have reached any purchase agreement with any other member prior to the suspension or termination and such agreement has been partially performed, Athena Crypto Bank may elect not to delete the transaction; provided, however, Athena Crypto Bank shall have the right to notify your counterparty of the situation at the same time of the suspension or termination.</Typography>
                
                <Typography component='h1'>Indemnity</Typography>
                <Typography>You shall indemnify Athena Crypto Bank and hold us harmless from and against all third-party claims except those resulting solely from Athena Crypto Bank 's breach of these Terms. Similarly, Athena Crypto Bank shall indemnify and hold you harmless from and against all third-party claims except those resulting solely from your breach of these Terms.</Typography>
                <ol  className='ol_li_mar_btm'>
                  <li>Athena Crypto Bank , as a third party platform for "network service provider", does not guarantee the information and services provided in this the site platform can fully meet the needs of users. Athena Crypto Bank shall not be liable for errors, insults, defamation, nonfeasance, obscenity, pornography, or blasphemy that may occur during the process of acceptance of the Athena Crypto Bank web service.</li>
                  <li>Based on the special nature of the Internet, Athena Crypto Bank does not guarantee that the service will not be interrupted, and the timeliness of the service, security are also not guaranteed, and Athena Crypto Bank do not bear the responsibility which is not caused by Athena Crypto Bank .Athena Crypto Bank tries to provide a safety network environment to the users, however, Athena Crypto Bank does not guarantee that the site or its servers are free of viruses or other potentially harmful factors; therefore, the user should use the industry's recognized software to check and kill any virus in the files downloaded from Athena Crypto Bank .</li>
                  <li>Athena Crypto Bank is not responsible for the failure of preservation, modification, deletion or storage of the information released by the user. Nor will Athena Crypto Bank be liable for the typographical errors, negligence, etc. not intentionally caused by Athena Crypto Bank .Athena Crypto Bank has the right but no obligation to improve or correct any omission, error of any part of this site.</li>
                  <li>Unless Athena Crypto Bank is expressly agreed in writing, Athena Crypto Bank shall not guarantee the accuracy, completeness, reliability of any content, such as, but not limited to, advertising from the Site in any manner (including but not limited to, containing, connecting, by way of, or downloading) from the Site; Athena Crypto Bank is not responsible for any products, services, information or materials purchased or obtained by the user according to the content information on this website. The user bears the risk of using the content of this website.</li>
                  <li>The user comments published by users in Athena Crypto Bank , are only on behalf of the user's personal point of view. It does not mean that this site agrees with their views or confirm their description. This site does not bear any legal responsibility caused by any user comments.</li>
                  <li>Athena Crypto Bank has the right to delete all types of information which does not meet the requirements of the laws or agreement, and Athena Crypto Bank retains the right not to inform the user.</li>
                  <li>In regards to notices issued to the users, Athena Crypto Bank will deliver these notices through a formal page announcement, station letter, e-mail, customer service phone call, SMS or regular mail delivery. Athena Crypto Bank does not bear any legal responsibility for any winning, discount activities or information which are delivered not by above channels.</li>
                  <li>Athena Crypto Bank has the right to adjust the recharge, commission, transaction and other fees according to market conditions, and have the right to decide the termination of the free promotion period.</li>
                </ol>
                <Typography component='h1'>Limitation of Liability</Typography>
                <Typography>In no event will Athena Crypto Bank , or its suppliers or licensors, be liable with respect to any subject matter of this agreement under any contract, negligence, strict liability or other legal or equitable theory for: * i) any special, incidental or consequential damages; (ii) the cost of procurement or substitute products or services; (iii) for interruption of use or loss or corruption of data; or (iv) for any amounts that exceed the fees paid by you to Athena Crypto Bank under this agreement during the twelve (12) month period prior to the cause of action. Athena Crypto Bank shall have no liability for any failure or delay due to matters beyond their reasonable control. Athena Crypto Bank will never be responsible for the loss caused by a trader contract, a project contract or other smart contracts offered to the end user.</Typography>
                <Typography component='h1'>Privacy Policy</Typography>
                <Typography>Athena Crypto Bank may announce and amend its privacy policy on the platform of Athena Crypto Bank from time to time and the privacy policy shall be an integral part of this agreement.</Typography>
              </Box>
          </Container>
        </Box>
    </>
  )
}
